### ISSUE TITLE
Packagist Namespace

### ISSUE THREAD

**Issue by m1guelpf** [laravel-frontend-presets/zurb-foundation#1]
Hi @Laraveldeep!

We would like to upload all our packages over packagist with the `laravel-frontend-presets` namespace, but when we try to add a new package, we get this:

> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at laravel-frontend-presets

Can you login into packagist and give that access, so we can manage the namespace and add new packages?

Thank you!

**Comment by OwenMelbz** [comment]
@laraveldeep is this something you can do? Then we can start unifying a bit more! :)

**Comment by m1guelpf** [comment]
@OwenMelbz This is something only @Laraveldeep can do.

**Comment by deeshrestha** [comment]
@m1guelpf @OwenMelbz Sorry I was out of town for few days.

Well I tried to submit https://github.com/laravel-frontend-presets/uikit3 but its an existing package under @OwenMelbz namespace. I think we need to change the namespace first?

**Comment by m1guelpf** [comment]
@Laraveldeep What you need to do is give us acces to the namespace so we can submit packages. To do so, you need to go to Packagist and give us write access to one of the packages under the namespace (like this one)

**Comment by deeshrestha** [comment]
Done... That white plus button was not so obvious :)

**Comment by OwenMelbz** [comment]
I've updated it for uikit as well now, so should all be in sync!
