### ISSUE TITLE
Preset Installation

### ISSUE THREAD

**Issue by bonge-ian** [laravel-frontend-presets/zurb-foundation#12]
This preset cant install with laravel 6 .
I keep getting an error as seen in the photo
![error](https://user-images.githubusercontent.com/35810849/66266768-f6dc4280-e818-11e9-8883-90656213b9e5.png)

**Comment by darryn-smith** [comment]
Try this:
`composer require laravel-frontend-presets/zurb-foundation:dev-master`

**Comment by bonge-ian** [comment]
Thanks @darryn-smith it worked
