### ISSUE TITLE
Update for Laravel 5.6

### ISSUE THREAD

**Issue by DominikPieper** [laravel-frontend-presets/zurb-foundation#5]
It's not working with the new Laravel release

**Comment by m1guelpf** [comment]
ping @laravel-frontend-presets/zurb-foundation-preset

**Comment by haykal78** [comment]
zurp foundation preset not working when upgrading to laravel 5.6

**Comment by OwenMelbz** [comment]
@haykal78 @nachtwandler would you like to submit a PR adding 5.6 as an option? I imagine its only because of the composer.json e.g https://github.com/laravel-frontend-presets/tailwindcss/blob/master/composer.json

**Comment by haykal78** [comment]
- Installation request for laravel/framework 5.6.3 -> satisfiable by laravel/framework[v5.6.3].
    - laravel-frontend-presets/zurb-foundation v1.2.1 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - laravel-frontend-presets/zurb-foundation v1.2.2 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - Conclusion: don't install laravel/framework 5.5.x-dev
    - Installation request for laravel-frontend-presets/zurb-foundation ^1.2.1 -> satisfiable by laravel-frontend-presets/zurb-foundation[v1.2.1, v1.2.2].

**Comment by haykal78** [comment]
i just wanna have foundation preset working on latest laravel

**Comment by deeshrestha** [comment]
Its fixed on new release.
