### ISSUE TITLE
laravel 5.7 installation issues

### ISSUE THREAD

**Issue by haykal78** [laravel-frontend-presets/zurb-foundation#6]
laravel preset produce this code when i'm trying to install this package to laravel 5.7

$ php artisan preset foundation

   ErrorException  : copy(D:\new_wamp\www\pamaned1\resources\assets/sass/_settings.scss): failed to open stream: No such file or directory

  at D:\new_wamp\www\pamaned1\vendor\laravel-frontend-presets\zurb-foundation\src\ZurbFoundationPreset.php:63
    59|         {
    60|             (new Filesystem)->delete($sass_file);
    61|         }
    62|
  > 63|         copy(__DIR__.'/foundation-stubs/_settings.scss', resource_path('assets/sass/_settings.scss'));
    64|         copy(__DIR__.'/foundation-stubs/foundation.scss', resource_path('assets/sass/foundation.scss'));
    65|         copy(__DIR__.'/foundation-stubs/app.scss', resource_path('assets/sass/app.scss'));
    66|     }
    67|

  Exception trace:

  1   copy("D:\new_wamp\www\pamaned1\vendor\laravel-frontend-presets\zurb-foundation\src/foundation-stubs/_settings.scss", "D:\new_wamp\www\pamaned1\resources\assets/sass/_settings.scss")
      D:\new_wamp\www\pamaned1\vendor\laravel-frontend-presets\zurb-foundation\src\ZurbFoundationPreset.php:63

  2   LaravelFrontendPresets\ZurbFoundationPreset\ZurbFoundationPreset::updateSass()
      D:\new_wamp\www\pamaned1\vendor\laravel-frontend-presets\zurb-foundation\src\ZurbFoundationPreset.php:19

please make it works for laravel 5.7 pliss @_@
  Please use the argument -v to see more details.

**Comment by m1guelpf** [comment]
Wanna make a PR?

**Comment by haykal78** [comment]
just wanna have the package to work that's all mate

**Comment by haykal78** [comment]
got it fixed

**Comment by haykal78** [comment]
got it fixed @_@

**Comment by drkhunter** [comment]
@haykal78 what was wrong? I'm having the same issue. Feel it's something silly.

**Comment by drkhunter** [comment]
I figured it out.  I was trying to set up v2 on Laravel 5.6.

**Comment by drkhunter** [comment]
> @haykal78 what was wrong? I'm having the same issue. Feel it's something silly.

I figured it out. I was trying to set up v2 on Laravel 5.6.
